[build]
  buildCommand = "npx prisma generate && npx prisma db push && npx tsx prisma/seed.ts && npm run build"

[deploy]
  startCommand = "npm run start"
  healthcheckPath = "/"
  healthcheckTimeout = 100

[volumes]
  "data" = "/data"
